# Generated by Django 5.0.4 on 2024-04-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(blank='false', choices=[('F', 'Fisica'), ('J', 'Juridica')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cip',
            field=models.CharField(blank='false', max_length=17),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank='false', max_length=150),
        ),
    ]
