# Generated by Django 5.0.4 on 2024-04-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cip',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('F', 'Fisica'), ('J', 'Juridica')], default='F', max_length=1),
        ),
    ]
