# Generated by Django 5.0.4 on 2024-04-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modelos_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cip', models.CharField(max_length=17)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(choices=[(1, 'teste')], max_length=50),
        ),
    ]
