# Generated by Django 5.0.4 on 2024-04-26 01:24

import app.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fonecedor_produto_created_at_alter_produto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelos',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name=app.core.models.Modelo),
        ),
    ]
