# Generated by Django 5.0.4 on 2024-04-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelos_created_at_alter_produto_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.DecimalField(choices=[(1, 'teste')], decimal_places=1, max_digits=1),
        ),
    ]
