# Generated by Django 5.0.4 on 2024-04-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_produto_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelos',
            name='valor',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(choices=[(1, 'teste')], default=1, max_length=1),
        ),
    ]
