# Generated by Django 5.0.4 on 2024-05-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_produto_modelo_alter_produto_preco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelos',
            new_name='Modelo',
        ),
    ]
