# Generated by Django 5.0.4 on 2024-05-02 01:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_modelos_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonecedor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
