# Generated by Django 5.0.4 on 2024-05-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cliente_id_alter_modelo_id_alter_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.IntegerField(auto_created=True, default=1),
        ),
    ]
