# Generated by Django 5.0.7 on 2024-07-14 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("horario", models.DateField()),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patologia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="paciente",
            name="medicamentos",
            field=models.ManyToManyField(
                related_name="pacientes", to="cuidar.medicamento"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="patologias",
            field=models.ManyToManyField(
                related_name="pacientes", to="cuidar.patologia"
            ),
        ),
    ]
