# Generated by Django 5.0.7 on 2024-07-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0004_remove_medicamento_dias_semana_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="medicamentos",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="patologias",
        ),
        migrations.AddField(
            model_name="medicamento",
            name="pacientes",
            field=models.ManyToManyField(
                related_name="medicamentos", to="cuidar.paciente"
            ),
        ),
        migrations.AddField(
            model_name="patologia",
            name="pacientes",
            field=models.ManyToManyField(
                related_name="patologias", to="cuidar.paciente"
            ),
        ),
    ]
