# Generated by Django 5.0.7 on 2024-08-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0005_remove_paciente_medicamentos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
