# Generated by Django 5.0.7 on 2024-08-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0007_alter_paciente_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paciente",
            old_name="cip",
            new_name="cpf",
        ),
        migrations.AddField(
            model_name="paciente",
            name="nacimento",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="sexo",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
