# Generated by Django 5.0.7 on 2024-08-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0008_rename_cip_paciente_cpf_paciente_nacimento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
