# Generated by Django 5.0.7 on 2024-08-01 01:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0009_alter_paciente_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
