# Generated by Django 5.0.7 on 2024-08-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0010_alter_paciente_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="genero",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="informacoes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="paciente",
            name="tipoSanguineo",
            field=models.CharField(
                choices=[("", ""), ("M", "Masculino"), ("F", "Feminino")],
                default="",
                max_length=1,
            ),
        ),
    ]
