# Generated by Django 5.0.7 on 2024-08-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0011_paciente_genero_paciente_informacoes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="sexo",
        ),
    ]
