# Generated by Django 5.0.7 on 2024-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0013_alter_paciente_genero_alter_paciente_tiposanguineo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="nacimento",
            field=models.DateField(),
        ),
    ]
