# Generated by Django 5.0.7 on 2024-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0014_alter_paciente_nacimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patologia",
            name="pacientes",
        ),
        migrations.AddField(
            model_name="patologia",
            name="paciente",
            field=models.ManyToManyField(related_name="paciente", to="cuidar.paciente"),
        ),
    ]
