# Generated by Django 5.0.7 on 2024-08-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0015_remove_patologia_pacientes_patologia_paciente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patologia",
            name="paciente",
            field=models.ManyToManyField(
                related_name="patologias", to="cuidar.paciente"
            ),
        ),
    ]
