# Generated by Django 5.0.7 on 2024-08-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuidar", "0016_alter_patologia_paciente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiaSemana",
        ),
        migrations.AddField(
            model_name="medicamento",
            name="dia",
            field=models.CharField(
                choices=[
                    ("SEG", "Segunda-feira"),
                    ("TER", "Terça-feira"),
                    ("QUA", "Quarta-feira"),
                    ("QUI", "Quinta-feira"),
                    ("SEX", "Sexta-feira"),
                    ("SAB", "Sábado"),
                    ("DOM", "Domingo"),
                ],
                default="",
                max_length=3,
            ),
        ),
    ]
